<?xml version="1.0" encoding="utf-8"?><Database Name="iot" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=iot;Persist Security Info=True;User ID=iot;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="iotConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Temp" Member="Temps">
    <Type Name="Temp">
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Temperature" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>